(() => {
  const shell=document.querySelector("[data-rag-chat]");if(!shell)return;
  const panel=shell.querySelector("[data-chat-panel]"),toggle=shell.querySelector("[data-chat-toggle]"),close=shell.querySelector("[data-chat-close]"),form=shell.querySelector("[data-chat-form]"),messages=shell.querySelector("[data-chat-messages]"),citations=shell.querySelector("[data-chat-citations]"),status=shell.querySelector("[data-chat-status]"),suggestions=shell.querySelector("[data-chat-suggestions]"),prefill=shell.querySelector("[data-chat-prefill]");
  let config=null,busy=false,lastAnswer="",history=[];
  const open=()=>{panel.hidden=false;toggle.setAttribute("aria-expanded","true");form.elements.message.focus()};
  const shut=()=>{panel.hidden=true;toggle.setAttribute("aria-expanded","false");toggle.focus()};
  const applyConfig=value=>{config=value;if(value?.feature_rag_chat===true&&value?.api_base_url){shell.hidden=false}else shell.hidden=true};
  window.addEventListener("portfolio:config",event=>applyConfig(event.detail));if(window.portfolioPlatform)applyConfig(window.portfolioPlatform);
  toggle.addEventListener("click",()=>panel.hidden?open():shut());close.addEventListener("click",shut);document.querySelectorAll("[data-open-chat]").forEach(x=>x.addEventListener("click",open));
  const bubble=(role,text="")=>{const el=document.createElement("div");el.className=`chat-message chat-message--${role}`;el.textContent=text;messages.append(el);messages.scrollTop=messages.scrollHeight;return el};
  const renderCitations=list=>{citations.replaceChildren();if(!list?.length)return;const title=document.createElement("strong");title.textContent="Sources";citations.append(title);list.forEach(source=>{const line=document.createElement("div"),a=document.createElement("a");a.textContent=`[${source.index}] ${source.title}`;a.href=source.url||"#";if(source.url){a.target="_blank";a.rel="noreferrer"}line.append(a);citations.append(line)})};
  async function ask(question){if(busy||!config?.api_base_url)return;busy=true;status.textContent="Retrieving portfolio evidence…";citations.replaceChildren();prefill.hidden=true;bubble("user",question);const answer=bubble("assistant","");let draft="",buffer="";
    try{const response=await fetch(`${String(config.api_base_url).replace(/\/$/,"")}/api/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:question,sessionId:config.sessionId,history:history.slice(-8)})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"The assistant is unavailable.")}const reader=response.body.getReader(),decoder=new TextDecoder();while(true){const{value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const blocks=buffer.split("\n\n");buffer=blocks.pop()||"";for(const block of blocks){let event="message",data="";for(const line of block.split("\n")){if(line.startsWith("event: "))event=line.slice(7);if(line.startsWith("data: "))data+=line.slice(6)}if(!data)continue;const payload=JSON.parse(data);if(event==="meta")renderCitations(payload.citations);if(event==="delta"){draft+=payload.text;answer.textContent=draft;messages.scrollTop=messages.scrollHeight}if(event==="done"){lastAnswer=payload.requestDraft?.problem||draft;prefill.hidden=!lastAnswer;status.textContent=payload.supported?"Grounded in the listed portfolio sources.":"Limited evidence found; use the request form for a scoped answer."}if(event==="error")throw new Error(payload.error)}if(done)break}history.push({role:"user",content:question},{role:"assistant",content:draft});history=history.slice(-8)}catch(error){answer.textContent=error.message;status.textContent="You can still use the project request form below."}finally{busy=false;form.elements.message.value=""}}
  form.addEventListener("submit",event=>{event.preventDefault();const q=form.elements.message.value.trim();if(q)ask(q)});suggestions.addEventListener("click",event=>{const button=event.target.closest("button");if(button)ask(button.textContent)});
  prefill.addEventListener("click",()=>{const request=document.querySelector("[data-request-form]");if(!request||!lastAnswer)return;const other=request.querySelector('input[name="service"][value="Other / Not sure"]'),stage=request.querySelector('input[name="projectStage"][value="New product"]');if(other)other.checked=true;if(stage)stage.checked=true;request.elements.problem.value=lastAnswer.slice(0,5000);request.dispatchEvent(new Event("input",{bubbles:true}));shut();document.querySelector("#request")?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});request.elements.problem.focus({preventScroll:true})});
  window.addEventListener("keydown",event=>{if(event.key==="Escape"&&!panel.hidden)shut()});
})();
