import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.95.0/+esm";
const projectUrl="https://hjdaprualapvzcsakbcd.supabase.co",publishableKey="sb_publishable_5RIwqitkK0bIky5SumAg4w_B9mjP29E";
const supabase=createClient(projectUrl,publishableKey,{auth:{persistSession:false}}),analyticsUrl=`${projectUrl}/functions/v1/track-event`,params=new URLSearchParams(location.search);
let sessionId=sessionStorage.getItem("kaushik-session-id");if(!sessionId){sessionId=crypto.randomUUID();sessionStorage.setItem("kaushik-session-id",sessionId)}
const track=(eventType,extra={})=>fetch(analyticsUrl,{method:"POST",headers:{"Content-Type":"application/json"},keepalive:true,body:JSON.stringify({eventType,sessionId,pagePath:location.pathname,referrerHost:document.referrer?new URL(document.referrer).hostname:null,utmSource:params.get("utm_source"),utmMedium:params.get("utm_medium"),utmCampaign:params.get("utm_campaign"),viewportWidth:innerWidth,website:"",...extra})}).catch(()=>{});
const price=s=>{const a=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:s.currency,maximumFractionDigits:0}).format(v/100);if(s.pricing_type==="custom")return"Custom quote";if(s.pricing_type==="range")return`${a(s.price_min)}–${a(s.price_max)}`;if(s.pricing_type==="starting_at")return`Starting at ${a(s.price_min)}`;return`${a(s.price_min)}${s.billing_unit==="month"?"/month":""}`};
async function loadServices(){const{data}=await supabase.from("services").select("id,slug,name,pricing_type,price_min,price_max,currency,billing_unit,delivery_time,cta_label").eq("is_published",true).order("sort_order");if(!data)return;const cards=[...document.querySelectorAll(".service-item")],positions={"ai-discovery-audit":0,"rag-document-ai":1,"agentic-workflow":2,"llm-evaluation-safety":3,"ai-ml-system":4,"ai-backend-api":5};data.forEach(s=>{const card=cards[positions[s.slug]];if(!card||card.querySelector(".service-price"))return;const block=document.createElement("div");block.className="service-price";block.dataset.serviceId=s.id;block.innerHTML=`<strong>${price(s)}</strong><small>${s.delivery_time||"Scoped after discovery"}</small><a href="#request">${s.cta_label} ↗</a>`;card.querySelector("div")?.append(block)})}
track("page_view");loadServices();
document.addEventListener("click",e=>{const link=e.target.closest("a,button");if(!link)return;const service=link.closest("[data-service-id]");if(service)track("cta_click",{serviceId:service.dataset.serviceId,section:"services"});else if(link.matches('a[href^="http"],a[href^="mailto:"]'))track("outbound_click",{metadata:{label:link.textContent.trim().slice(0,80)}})});
const form=document.querySelector("[data-request-form]");form?.addEventListener("input",()=>track("form_start",{section:"request"}),{once:true});window.addEventListener("portfolio:lead-submitted",()=>track("form_submit",{section:"request"}));
const seen=new Set(),observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const id=entry.target.id;if(entry.isIntersecting&&id&&!seen.has(id)){seen.add(id);track("section_view",{section:id})}}),{threshold:.4});document.querySelectorAll("main > section[id]").forEach(s=>observer.observe(s));
