let c;
const setting = key => c?.state.settings.find(x => x.setting_key === key)?.setting_value;
const uid = () => crypto.randomUUID();
const iso = value => value ? new Date(value).toISOString() : null;
const lines = value => String(value || "").split(/\n|,/).map(x => x.trim()).filter(Boolean);
const amount = value => Math.round(Number(value || 0) * 100);
const row = (label, value, tag = "") => `<div class="row"><span>${c.esc(label)}<br><small>${c.esc(value || "")}</small></span>${tag ? `<span class="tag">${c.esc(tag)}</span>` : ""}</div>`;

async function api(path, options = {}) {
  const base = String(setting("api_base_url") || "").replace(/\/$/, "");
  if (!base) throw new Error("Set the hosted API URL in Settings first.");
  const { data: { session } } = await c.db.auth.getSession();
  const response = await fetch(`${base}${path}`, { ...options, headers: { "content-type": "application/json", authorization: `Bearer ${session?.access_token}`, ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(data.error || `API returned ${response.status}`), { data });
  return data;
}

function renderSources() {
  c.$("[data-source-configs]").innerHTML = c.state.sources.map(x => row(x.name, `${x.start_urls?.[0] || "No URL"} · next ${c.date(x.next_run_at)}`, x.is_enabled ? "enabled" : "paused")).join("") || "<p class=muted>No scan sources yet.</p>";
  c.$("[data-discovered-leads]").innerHTML = c.state.discoveries.map(x => `<div class="ops-record"><div><span class="tag">${c.esc(x.review_status)} · ${x.score}/100</span><h3>${c.esc(x.company_name)}</h3><p>${c.esc(x.evidence)}</p><a href="${c.esc(x.source_url)}" target="_blank" rel="noreferrer">Review evidence ↗</a></div><div><label>Verified public email<input type="email" data-discovery-email="${x.id}" placeholder="name@company.com"></label><div class="actions"><button data-discovery-approve="${x.id}">Approve to CRM</button><button class="ghost" data-discovery-reject="${x.id}">Reject</button></div></div></div>`).join("") || "<p class=muted>No discoveries awaiting review.</p>";
}

function renderOutreach() {
  c.$("[data-campaigns]").innerHTML = c.state.campaigns.map(x => row(x.name, `${x.daily_draft_limit} drafts/day · ${c.state.recipients.filter(r => r.campaign_id === x.id).length} recipients`, x.status)).join("") || "<p class=muted>No campaigns yet.</p>";
  c.$("[data-outreach-messages]").innerHTML = c.state.outreachMessages.map(x => `<div class="ops-record"><div><span class="tag">${c.esc(x.status)} · step ${x.sequence_step}</span><h3>${c.esc(x.subject)}</h3><p class="preline">${c.esc(x.body_text)}</p></div><div class="actions">${x.status === "generated" ? `<button data-message-approve="${x.id}">Approve</button>` : ""}${x.status === "approved" ? `<button data-gmail-draft="${x.id}">Create Gmail draft</button>` : ""}<small>${x.gmail_draft_id ? "Draft created — never sent" : ""}</small></div></div>`).join("") || "<p class=muted>No generated messages.</p>";
}

function renderPricing() {
  c.$("[data-estimates]").innerHTML = c.state.estimates.map(x => `<div class="row"><span>${c.esc(x.estimate_number)} · ${c.esc(x.title)}<br><small>${c.esc(x.client_name || "No client")}${x.below_floor ? " · BELOW FLOOR" : ""}</small></span><strong>${c.money(x.total, x.currency)}</strong></div>`).join("") || "<p class=muted>No estimates yet.</p>";
  c.$("[data-proposals]").innerHTML = c.state.proposals.map(x => `<div class="row"><span>${c.esc(x.proposal_number)} v${x.version} · ${c.esc(x.client_name)}<br><small>${c.esc(x.status)} · ${c.date(x.created_at)}</small></span><span class="actions"><strong>${c.money(x.total,x.currency)}</strong><button class="ghost" data-render-proposal="${x.id}">PDF</button></span></div>`).join("") || "<p class=muted>No proposals yet.</p>";
}

function renderFinance() {
  const income = c.state.transactions.filter(x => x.transaction_type === "income").reduce((n,x) => n + Number(x.reporting_amount), 0);
  const expenses = c.state.transactions.filter(x => x.transaction_type === "expense" && !x.is_pass_through).reduce((n,x) => n + Number(x.reporting_amount), 0);
  const outstanding = c.state.invoices.reduce((n,x) => n + Number(x.total) - Number(x.amount_paid), 0);
  const overdue = c.state.invoices.filter(x => x.due_on && new Date(x.due_on) < new Date() && x.status !== "paid").length;
  c.$("[data-finance-metrics]").innerHTML = [["Cash income",c.money(income,"USD")],["Operating costs",c.money(expenses,"USD")],["Cash margin",income ? `${((income-expenses)/income*100).toFixed(1)}%` : "0%"],["Outstanding",`${c.money(outstanding,"USD")} · ${overdue} overdue`]].map(x => `<div class=metric><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");
  c.$("[data-transactions]").innerHTML = c.state.transactions.slice(0,50).map(x => row(x.description, `${x.category} · ${c.date(x.transaction_date)}`, `${x.transaction_type} ${c.money(x.amount,x.currency)}`)).join("") || "<p class=muted>No transactions.</p>";
  c.$("[data-invoices]").innerHTML = c.state.invoices.map(x => row(`${x.invoice_number} · ${x.client_name}`, `due ${c.date(x.due_on)}`, `${x.status} ${c.money(x.total,x.currency)}`)).join("") || "<p class=muted>No invoices.</p>";
}

function renderReferrals() { c.$("[data-referrals]").innerHTML = c.state.referrals.map(x => row(x.referrer_name, `${x.referred_name || "Introduction pending"} · follow up ${c.date(x.next_follow_up_at)}`, `${x.status} · ${x.reward_status}`)).join("") || "<p class=muted>No referral requests.</p>"; }

function renderContent() {
  const filter = c.$("[data-content-filter]").value;
  c.$("[data-content-items]").innerHTML = c.state.content.filter(x => !filter || x.status === filter).map(x => `<div class="ops-record"><div><span class="tag">${c.esc(x.pillar)} · ${c.esc(x.status)}</span><h3>${c.esc(x.title)}</h3>${x.linkedin_content ? `<details><summary>LinkedIn draft</summary><p class="preline">${c.esc(x.linkedin_content)}</p></details>` : ""}${x.github_content ? `<details><summary>GitHub draft</summary><p class="preline">${c.esc(x.github_content)}</p></details>` : ""}</div><div class="actions">${x.status === "review" ? `<button data-content-approve="${x.id}">Approve</button>` : ""}${x.status === "approved" ? `<button data-content-github="${x.id}">Publish GitHub</button><button class="ghost" data-content-linkedin="${x.id}">Publish LinkedIn</button>` : ""}<button class="ghost" data-content-copy="${x.id}">Copy</button></div></div>`).join("") || "<p class=muted>No content in this view.</p>";
}

function renderSop() {
  c.$("[data-sop-documents]").innerHTML = c.state.sops.map(doc => `<article><span class="tag">v${doc.version} · ${c.esc(doc.status)}</span><h3>${c.esc(doc.title)}</h3><p>${c.esc(doc.purpose)}</p><ol class="sop-list">${c.state.sopSteps.filter(x => x.sop_document_id === doc.id).map(x => `<li><strong>${c.esc(x.stage)} — ${c.esc(x.title)}</strong><p>${c.esc(x.instructions)}</p><small>Done when: ${c.esc(x.completion_rule)}</small></li>`).join("")}</ol></article>`).join("");
  c.$("[data-sop-runs]").innerHTML = c.state.sopRuns.map(x => row(x.run_name, `${x.checklist.filter(i=>i.done).length}/${x.checklist.length} complete · started ${c.date(x.started_at)}`, x.status)).join("") || "<p class=muted>No checklist runs.</p>";
}

function renderRag() {
  c.$("[data-knowledge-documents]").innerHTML = c.state.knowledge.map(x => `<div class=row><span>${c.esc(x.title)}<br><small>${c.esc(x.document_type)} · ${c.date(x.updated_at)}</small></span><span class=tag>${c.esc(x.embedding_status)}${x.is_published ? " · public" : ""}</span></div>`).join("") || "<p class=muted>No knowledge documents.</p>";
  c.$("[data-rag-metrics]").innerHTML = c.state.ragMetrics.slice(0,30).map(x => row(`${x.answer_supported ? "Grounded" : "Fallback"} · ${x.latency_ms}ms`, `${x.input_tokens + x.output_tokens} tokens · ${c.date(x.created_at)}`, x.model_id)).join("") || "<p class=muted>No chat queries yet.</p>";
}

function renderSettings() {
  const f=c.$("[data-settings-form]"); ["api_base_url","usd_inr_rate","tax_reserve_percent"].forEach(k => f.elements[k].value=setting(k) ?? ""); ["feature_rag_chat","feature_lead_scanner","feature_gmail_drafts","feature_content_publish"].forEach(k => f.elements[k].checked=setting(k)===true);
  c.$("[data-integrations]").innerHTML = c.state.integrations.map(x => row(x.provider, `${x.account_label || "No account"} · checked ${c.date(x.last_checked_at)}`, x.status)).join("") || "<p class=muted>No integrations connected.</p>";
  c.$("[data-audit-log]").innerHTML = c.state.audits.slice(0,40).map(x => row(`${x.action} · ${x.entity_type}`, `${x.entity_id || ""} · ${c.date(x.created_at)}`)).join("") || "<p class=muted>No audit events.</p>";
}

export function renderOpsModules() { if(!c)return; renderSources(); renderOutreach(); renderPricing(); renderFinance(); renderReferrals(); renderContent(); renderSop(); renderRag(); renderSettings(); }

export function initOpsModules(context) {
  c=context;
  const reload = async success => { await c.loadAll(); c.message(success); };
  c.$("[data-source-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),url=String(f.get("start_url")),domain=new URL(url).hostname.replace(/^www\./,"");const{data,error}=await c.db.from("lead_source_configs").insert({name:f.get("name"),start_urls:[url],allowed_domains:[domain],service_keywords:lines(f.get("keywords")),exclusion_keywords:lines(f.get("exclusions")),is_enabled:f.get("is_enabled")==="on",next_run_at:new Date().toISOString()}).select().single();if(error)return c.message(error.message,true);await c.audit("create","lead_source_config",data.id,null,data);e.currentTarget.reset();await reload("Source saved. The worker will scan it when enabled.")});
  c.$("[data-discovered-leads]").addEventListener("click",async e=>{const approve=e.target.closest("[data-discovery-approve]"),reject=e.target.closest("[data-discovery-reject]");if(reject){await c.db.from("discovered_leads").update({review_status:"rejected",reviewed_by:c.state.user.id,reviewed_at:new Date().toISOString()}).eq("id",reject.dataset.discoveryReject);return reload("Discovery rejected.")}if(approve){const x=c.state.discoveries.find(v=>v.id===approve.dataset.discoveryApprove),email=c.$(`[data-discovery-email="${x.id}"]`).value.trim();if(!email)return c.message("Enter a verified public business email before approval.",true);const{data:lead,error}=await c.db.from("lead_requests").insert({service:x.matched_service||"AI system",project_stage:"Research signal",project_name:x.company_name,problem:x.evidence,budget:"To qualify",timeline:"To qualify",needs:[],contact_name:x.company_name,contact_email:email,company:x.company_name,relevant_link:x.source_url,consent:true,source:"lead_finder",pipeline_stage:"inbox"}).select().single();if(error)return c.message(error.message,true);await c.db.from("discovered_leads").update({review_status:"approved",reviewed_by:c.state.user.id,reviewed_at:new Date().toISOString(),lead_request_id:lead.id}).eq("id",x.id);await reload("Discovery approved into the CRM. No outreach was sent.")}});
  c.$("[data-campaign-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),sequence=[{step:1,delay_days:0},{step:2,delay_days:3},{step:3,delay_days:7},{step:4,delay_days:14}];const{error}=await c.db.from("outreach_campaigns").insert({name:f.get("name"),daily_draft_limit:Number(f.get("daily_draft_limit")),status:f.get("status"),sequence});if(error)return c.message(error.message,true);e.currentTarget.reset();await reload("Draft-only campaign saved.")});
  c.$("[data-outreach-messages]").addEventListener("click",async e=>{const approve=e.target.closest("[data-message-approve]"),draft=e.target.closest("[data-gmail-draft]");if(approve){await c.db.from("outreach_messages").update({status:"approved",approved_by:c.state.user.id,approved_at:new Date().toISOString()}).eq("id",approve.dataset.messageApprove);return reload("Message approved. It has not been sent.")}if(draft){try{await api("/api/outreach/gmail-drafts",{method:"POST",body:JSON.stringify({messageIds:[draft.dataset.gmailDraft]})});await reload("Gmail draft created. Nothing was sent.")}catch(error){c.message(error.message,true)}}});
  c.$("[data-connect-gmail]").addEventListener("click",async()=>{try{const{url}=await api("/api/oauth/google/start",{method:"GET"});location.href=url}catch(error){c.message(error.message,true)}});
  const preview=()=>{const f=new FormData(c.$("[data-pricing-form]")),subtotal=Number(f.get("quantity")||0)*Number(f.get("unit_amount")||0),contingency=subtotal*Number(f.get("contingency_percent")||0)/100,tax=(subtotal+contingency)*Number(f.get("tax_percent")||0)/100,total=subtotal+contingency+tax,cost=Number(f.get("cost_amount")||0),margin=total?((total-cost)/total*100):0,floor=Number(f.get("price_floor")||0);c.$("[data-estimate-preview]").innerHTML=`<strong>${c.esc(String(f.get("currency")))} ${total.toLocaleString()}</strong><small>${margin.toFixed(1)}% margin${total<floor?" · BELOW FLOOR":""}</small>`;return{subtotal,contingency,tax,total,cost,margin,below:total<floor}};
  c.$("[data-pricing-form]").addEventListener("input",preview);preview();
  c.$("[data-pricing-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),x=preview(),number=`EST-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(c.state.estimates.length+1).padStart(3,"0")}`;const{data,error}=await c.db.from("estimates").insert({estimate_number:number,title:f.get("title"),client_name:f.get("client_name")||null,currency:f.get("currency"),subtotal:amount(x.subtotal),contingency:amount(x.contingency),tax_amount:amount(x.tax),total:amount(x.total),margin_percent:x.margin,below_floor:x.below,created_by:c.state.user.id}).select().single();if(error)return c.message(error.message,true);await c.db.from("estimate_items").insert({estimate_id:data.id,description:f.get("title"),pricing_mode:f.get("pricing_mode"),quantity:Number(f.get("quantity")),unit_amount:amount(f.get("unit_amount")),cost_amount:amount(f.get("cost_amount")),total_amount:amount(x.subtotal)});e.currentTarget.reset();await reload("Estimate saved.")});
  c.$("[data-proposal-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),number=`PROP-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(c.state.proposals.length+1).padStart(3,"0")}`;const{error}=await c.db.from("proposals").insert({proposal_number:number,title:f.get("title"),client_name:f.get("client_name"),currency:f.get("currency"),total:amount(f.get("total")),content:{summary:f.get("summary"),scope:f.get("scope"),timeline:f.get("timeline"),assumptions:lines(f.get("assumptions"))},created_by:c.state.user.id,idempotency_key:uid()});if(error)return c.message(error.message,true);e.currentTarget.reset();await reload("Proposal saved.")});
  c.$("[data-proposals]").addEventListener("click",async e=>{const button=e.target.closest("[data-render-proposal]");if(!button)return;try{const result=await api("/api/proposals/render",{method:"POST",body:JSON.stringify({proposalId:button.dataset.renderProposal})});window.open(result.downloadUrl,"_blank","noopener");c.message("Private PDF generated with a ten-minute download link.")}catch(error){c.message(error.message,true)}});
  c.$("[data-transaction-form]").elements.transaction_date.value=new Date().toISOString().slice(0,10);c.$("[data-invoice-form]").elements.issued_on.value=new Date().toISOString().slice(0,10);
  c.$("[data-transaction-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),currency=String(f.get("currency")),raw=amount(f.get("amount")),rate=Number(f.get("exchange_rate")),reporting=currency==="USD"?raw:Math.round(raw/rate);const{error}=await c.db.from("financial_transactions").insert({transaction_date:f.get("transaction_date"),transaction_type:f.get("transaction_type"),category:f.get("category"),description:f.get("description"),amount:raw,currency,reporting_amount:reporting,reporting_currency:"USD",exchange_rate:rate,is_pass_through:f.get("is_pass_through")==="on"});if(error)return c.message(error.message,true);e.currentTarget.reset();await reload("Cash transaction recorded.")});
  c.$("[data-invoice-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),number=`INV-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(c.state.invoices.length+1).padStart(3,"0")}`,total=amount(f.get("total"));const{error}=await c.db.from("invoices").insert({invoice_number:number,client_name:f.get("client_name"),client_email:f.get("client_email")||null,currency:f.get("currency"),subtotal:total,total,issued_on:f.get("issued_on"),due_on:f.get("due_on")||null});if(error)return c.message(error.message,true);e.currentTarget.reset();await reload("Invoice saved.")});
  c.$("[data-referral-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await c.db.from("referral_requests").insert({referrer_name:f.get("referrer_name"),referrer_email:f.get("referrer_email")||null,status:f.get("status"),next_follow_up_at:iso(f.get("next_follow_up_at")),reward_description:f.get("reward_description")||null});if(error)return c.message(error.message,true);e.currentTarget.reset();await reload("Referral request saved with manual reward review.")});
  c.$("[data-content-filter]").addEventListener("change",renderContent);c.$("[data-content-items]").addEventListener("click",async e=>{const approve=e.target.closest("[data-content-approve]"),github=e.target.closest("[data-content-github]"),linkedin=e.target.closest("[data-content-linkedin]"),copy=e.target.closest("[data-content-copy]");if(approve){await c.db.from("content_items").update({status:"approved"}).eq("id",approve.dataset.contentApprove);return reload("Content approved.")}const id=github?.dataset.contentGithub||linkedin?.dataset.contentLinkedin;if(id){try{await api(`/api/content/publish/${github?"github":"linkedin"}`,{method:"POST",body:JSON.stringify({contentId:id})});return reload(`Published to ${github?"GitHub":"LinkedIn"}.`)}catch(error){if(error.data?.fallback){await navigator.clipboard.writeText(error.data.fallback);return c.message(`${error.message}; draft copied for manual publishing.`,true)}return c.message(error.message,true)}}if(copy){const x=c.state.content.find(v=>v.id===copy.dataset.contentCopy);await navigator.clipboard.writeText(x.linkedin_content||x.github_content||x.title);c.message("Content copied.")}});
  c.$("[data-start-sop]").addEventListener("click",async()=>{const doc=c.state.sops.find(x=>x.status==="approved")||c.state.sops[0];if(!doc)return c.message("No SOP available.",true);const checklist=c.state.sopSteps.filter(x=>x.sop_document_id===doc.id).map(x=>({step_id:x.id,title:x.title,done:false}));const{error}=await c.db.from("sop_runs").insert({sop_document_id:doc.id,run_name:`Simulated lifecycle ${new Date().toLocaleDateString("en-IN")}`,checklist});if(error)return c.message(error.message,true);await reload("Simulated SOP run started.")});
  c.$("[data-knowledge-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const{data,error}=await c.db.from("knowledge_documents").insert({title:f.get("title"),slug:f.get("slug"),document_type:f.get("document_type"),source_url:f.get("source_url")||null,content:f.get("content"),is_published:f.get("is_published")==="on",embedding_status:"pending"}).select().single();if(error)return c.message(error.message,true);await c.audit("create","knowledge_document",data.id,null,{title:data.title});e.currentTarget.reset();await reload("Knowledge saved and queued for indexing.")});
  c.$("[data-settings-form]").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),rows=["api_base_url","usd_inr_rate","tax_reserve_percent"].map(k=>({setting_key:k,setting_value:k==="api_base_url"?String(f.get(k)||""):Number(f.get(k)||0),is_public:k==="api_base_url"}));for(const k of ["feature_rag_chat","feature_lead_scanner","feature_gmail_drafts","feature_content_publish"])rows.push({setting_key:k,setting_value:f.get(k)==="on",is_public:k==="feature_rag_chat"});const{error}=await c.db.from("site_settings").upsert(rows,{onConflict:"setting_key"});if(error)return c.message(error.message,true);await reload("Platform settings saved.")});
}
