create index discovered_leads_source_run_idx on public.discovered_leads (source_run_id) where source_run_id is not null;
create index discovered_leads_lead_request_idx on public.discovered_leads (lead_request_id) where lead_request_id is not null;
create index discovered_leads_reviewed_by_idx on public.discovered_leads (reviewed_by) where reviewed_by is not null;
create index estimate_items_service_idx on public.estimate_items (service_id) where service_id is not null;
create index estimates_project_idx on public.estimates (project_id) where project_id is not null;
create index estimates_pricing_profile_idx on public.estimates (pricing_profile_id) where pricing_profile_id is not null;
create index estimates_created_by_idx on public.estimates (created_by);
create index proposals_estimate_idx on public.proposals (estimate_id) where estimate_id is not null;
create index proposals_project_idx on public.proposals (project_id) where project_id is not null;
create index proposals_template_idx on public.proposals (template_id) where template_id is not null;
create index proposals_created_by_idx on public.proposals (created_by);
create index outreach_recipients_lead_idx on public.outreach_recipients (lead_request_id) where lead_request_id is not null;
create index outreach_recipients_discovery_idx on public.outreach_recipients (discovered_lead_id) where discovered_lead_id is not null;
create index outreach_messages_approved_by_idx on public.outreach_messages (approved_by) where approved_by is not null;
create index invoices_project_idx on public.invoices (project_id) where project_id is not null;
create index invoices_proposal_idx on public.invoices (proposal_id) where proposal_id is not null;
create index financial_transactions_invoice_idx on public.financial_transactions (invoice_id) where invoice_id is not null;
create index referral_requests_lead_idx on public.referral_requests (lead_request_id) where lead_request_id is not null;
create index referral_requests_project_idx on public.referral_requests (project_id) where project_id is not null;
create index sop_runs_document_idx on public.sop_runs (sop_document_id);
create index sop_runs_project_idx on public.sop_runs (project_id) where project_id is not null;
